version: "3.8"
services:
  mysql-service:
    image: localhost:5000/registry-mysql
    container_name: mysql-service
    ports:
      - "3306:3306"
    networks:
      - projetNetwork
    volumes:
      - volmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testdb"
  projetbackend:
    image: localhost:5000/registry-projetbackend
    container_name: projetbackend
    ports:
      - "8080:8080"
    networks:
      - projetNetwork
    depends_on:
      - mysql-service
  projetfrontend:
    image: localhost:5000/registry-projetfrontend
    container_name: projetfrontend
    ports:
      - "8081:80"
    networks:
      - projetNetwork
    depends_on:
      - projetbackend
volumes:
  volmysql:
    driver: local
networks:
  projetNetwork:
    driver: bridge