apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: exam
subjects:
- kind: User
  name: "ahmedelbaz771@gmail.com"  
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exam-role
  apiGroup: rbac.authorization.k8s.io
